import React, { useState } from 'react';
import JSZip from 'jszip';
import { KOTLIN_PROJECT_FILES, KotlinFile } from '../data/kotlinBundle';
import { X, Download, Copy, Check, FileCode, Folder, ShieldCheck } from 'lucide-react';

interface KotlinProjectModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const KotlinProjectModal: React.FC<KotlinProjectModalProps> = ({ isOpen, onClose }) => {
  const [selectedFileIndex, setSelectedFileIndex] = useState<number>(0);
  const [copied, setCopied] = useState<boolean>(false);
  const [isExporting, setIsExporting] = useState<boolean>(false);

  if (!isOpen) return null;

  const currentFile: KotlinFile = KOTLIN_PROJECT_FILES[selectedFileIndex] || KOTLIN_PROJECT_FILES[0];

  const handleCopyCode = async () => {
    try {
      await navigator.clipboard.writeText(currentFile.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
    }
  };

  const handleDownloadZip = async () => {
    try {
      setIsExporting(true);
      const zip = new JSZip();

      // Add project readme
      zip.file(
        'README.md',
        `# X Board Keyboard - Android 8.0+ (API 26) Kotlin Project
Generated by X Board Keyboard Engine.

## How to build in Android Studio:
1. Open Android Studio -> "Open an Existing Project".
2. Select this unzipped folder.
3. Sync Gradle and Run on device / emulator (Android 8.0 Oreo or higher).
4. Go to Settings -> System -> Languages & Input -> Virtual Keyboard -> Manage Keyboards.
5. Enable **X Board English Keyboard**!
`
      );

      // Add all project files
      KOTLIN_PROJECT_FILES.forEach((f) => {
        zip.file(f.path, f.content);
      });

      const blob = await zip.generateAsync({ type: 'blob' });
      const downloadUrl = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = downloadUrl;
      a.download = 'XBoard-Keyboard-Android-Kotlin-Project.zip';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(downloadUrl);
    } catch (err) {
      console.error('Failed to create zip', err);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div
      id="kotlin-project-modal-overlay"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-sm p-3 md:p-6"
    >
      <div
        id="kotlin-project-modal-card"
        className="w-full max-w-4xl h-[85vh] bg-[#121216] border-2 border-[#07f57e] rounded-2xl flex flex-col shadow-2xl overflow-hidden"
      >
        {/* Modal Header */}
        <div className="bg-[#18181f] px-4 py-3 flex items-center justify-between border-b border-[#252530]">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-[#07f57e] flex items-center justify-center text-black font-extrabold text-sm">
              K
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-bold text-white">
                  Android 8.0+ Kotlin Source Code
                </h3>
                <span className="px-2 py-0.5 bg-[#07f57e]/20 text-[#07f57e] text-[10px] font-mono font-bold rounded border border-[#07f57e]/30 flex items-center gap-1">
                  <ShieldCheck className="w-3 h-3" />
                  API 26+ Oreo Ready
                </span>
              </div>
              <p className="text-[11px] text-neutral-400">
                Native InputMethodService, 24 Unicode fonts, 20 Text styles & AdMob support
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              id="btn-download-kotlin-zip"
              onClick={handleDownloadZip}
              disabled={isExporting}
              className="px-3.5 py-1.5 bg-[#07f57e] hover:bg-[#07f57e]/90 text-black font-bold text-xs rounded-lg transition active:scale-95 shadow flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
            >
              <Download className="w-3.5 h-3.5" />
              <span>{isExporting ? 'Generating ZIP...' : 'Download Android Studio ZIP'}</span>
            </button>

            <button
              id="btn-close-kotlin-modal"
              onClick={onClose}
              className="p-1.5 rounded-lg text-neutral-400 hover:text-white hover:bg-[#252532] cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body: File Tree Sidebar & Code Viewer */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
          {/* File List */}
          <div className="w-full md:w-72 bg-[#141418] border-r border-[#22222a] p-2 overflow-y-auto scrollbar-thin">
            <div className="text-[10px] font-mono uppercase tracking-wider text-neutral-400 px-2 py-1.5 flex items-center gap-1">
              <Folder className="w-3.5 h-3.5 text-[#07f57e]" />
              <span>Project Files</span>
            </div>
            <div className="space-y-1">
              {KOTLIN_PROJECT_FILES.map((f, idx) => (
                <button
                  key={f.path}
                  id={`file-item-${idx}`}
                  onClick={() => setSelectedFileIndex(idx)}
                  className={`w-full text-left p-2 rounded-lg transition flex items-center gap-2 cursor-pointer ${
                    selectedFileIndex === idx
                      ? 'bg-[#07f57e]/15 border border-[#07f57e] text-white'
                      : 'bg-transparent text-neutral-400 hover:bg-[#1a1a22] hover:text-neutral-200'
                  }`}
                >
                  <FileCode className={`w-3.5 h-3.5 shrink-0 ${selectedFileIndex === idx ? 'text-[#07f57e]' : 'text-neutral-500'}`} />
                  <div className="truncate">
                    <span className="text-xs font-mono font-medium block truncate">
                      {f.filename}
                    </span>
                    <span className="text-[10px] text-neutral-500 block truncate">
                      {f.path.split('/')[f.path.split('/').length - 2] || 'root'}
                    </span>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Code Viewer Panel */}
          <div className="flex-1 flex flex-col bg-[#0d0d10] overflow-hidden">
            <div className="px-4 py-2 bg-[#121216] border-b border-[#202028] flex items-center justify-between">
              <div className="flex flex-col">
                <span className="text-xs font-mono text-[#07f57e] font-semibold">
                  {currentFile.path}
                </span>
                <span className="text-[10px] text-neutral-400">
                  {currentFile.description}
                </span>
              </div>

              <button
                id="btn-copy-current-code"
                onClick={handleCopyCode}
                className="px-2.5 py-1 rounded bg-[#202028] hover:bg-[#282834] text-xs font-semibold text-white flex items-center gap-1.5 transition active:scale-95 border border-[#2d2d38] cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-[#07f57e]" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied!' : 'Copy Code'}</span>
              </button>
            </div>

            <pre className="flex-1 p-4 text-xs font-mono text-neutral-200 overflow-auto scrollbar-thin leading-relaxed">
              <code>{currentFile.content}</code>
            </pre>
          </div>
        </div>

        {/* Modal Footer Info */}
        <div className="px-4 py-2 bg-[#18181f] border-t border-[#252530] text-[11px] text-neutral-400 flex items-center justify-between font-mono">
          <span>Android SDK: minSdk 26 (Android 8.0 Oreo) • compileSdk 34 • Kotlin 1.9+</span>
          <span className="text-[#07f57e]">X Board Engine v1.0.0</span>
        </div>
      </div>
    </div>
  );
};
